version: '3'

services:
  database:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=cardapio"
    networks:
      - 'project-network'
    ports:
      - '5432:5432' 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=projetomenu@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=postgres"
    networks:
      - 'project-network'
    ports:
      - '15432:80'
networks:
  project-network:
    driver: bridge