# Generated by Django 4.2.7 on 2023-12-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id_cardapio', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
                'db_table': 'cardapio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaFuncionamento',
            fields=[
                ('id_dia_funcionamento', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, max_length=60, null=True)),
                ('data_dia', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dia de Funcionamento',
                'verbose_name_plural': 'Dias de Funcionamento',
                'db_table': 'dia_funcionamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('nota_refeicao', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refeicoes',
            fields=[
                ('id_refeicoes', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prato', models.CharField(blank=True, max_length=60, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'db_table': 'refeicoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('senha', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('data_modificacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
